variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'backendaccountserviceregistry'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'backendaccountserviceregistry'
  serviceName: 'prdrwdwebwa1407'
  kvName: PRDRWDINFKV1401
  sqlDBserver: prdrwddbssq1401.database.windows.net
  sqlDB: 'prd1_accounts'
  validationApiServiceName: 'prdrwdwebfa1407'
  validationApiRepository: 'validationdataapiregistry'