version: '3.4'
name: backend-account-service
services:
  backendaccountservice.api:
    build:
      context: .
      dockerfile: BackendAccountService.Api/DockerfileLocal
      args:
        TRUSTED_CERT: certs/kainos-chain.pem
        PORT: 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AccountsDatabase=Server=accountsdb_sql,1433;Initial Catalog=AccountsDb;User Id=sa;Password=Password1!;TrustServerCertificate=True;
    depends_on:
      - accountsdb_sql

  accountsdb_sql:
    image: mcr.microsoft.com/azure-sql-edge
    restart: always
    cap_add:
      - SYS_PTRACE
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Password1!